-- autogenerated lush spec on Thu Jul  7 11:46:17 2022
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function()
  return {
    Boolean { gui = "bold", fg = "#c57825", }, -- Boolean        xxx ctermfg=103 gui=bold guifg=#c57825
    Character { gui = "italic", fg = "#9676ac", }, -- Character      xxx ctermfg=103 gui=italic guifg=#9676ac
    CmpItemAbbr { CmpItemAbbrDefault }, -- CmpItemAbbr    xxx links to CmpItemAbbrDefault
    CmpItemAbbrDefault {}, -- CmpItemAbbrDefault xxx cterm= gui=
    CmpItemAbbrDeprecated { CmpItemAbbrDeprecatedDefault }, -- CmpItemAbbrDeprecated xxx links to CmpItemAbbrDeprecatedDefault
    CmpItemAbbrDeprecatedDefault { fg = "#0000f4", }, -- CmpItemAbbrDeprecatedDefault xxx cterm= gui= guifg=#0000f4
    CmpItemAbbrMatch { CmpItemAbbrMatchDefault }, -- CmpItemAbbrMatch xxx links to CmpItemAbbrMatchDefault
    CmpItemAbbrMatchDefault {}, -- CmpItemAbbrMatchDefault xxx cterm= gui=
    CmpItemAbbrMatchFuzzy { CmpItemAbbrMatchFuzzyDefault }, -- CmpItemAbbrMatchFuzzy xxx links to CmpItemAbbrMatchFuzzyDefault
    CmpItemAbbrMatchFuzzyDefault {}, -- CmpItemAbbrMatchFuzzyDefault xxx cterm= gui=
    CmpItemKind { CmpItemKindDefault }, -- CmpItemKind    xxx links to CmpItemKindDefault
    CmpItemKindDefault { fg = "#0000ac", }, -- CmpItemKindDefault xxx cterm= gui= guifg=#0000ac
    CmpItemMenu { CmpItemMenuDefault }, -- CmpItemMenu    xxx links to CmpItemMenuDefault
    CmpItemMenuDefault {}, -- CmpItemMenuDefault xxx cterm= gui=
    ColorColumn { bg = "#313335", }, -- ColorColumn    xxx ctermbg=236 guibg=#313335
    Comment { fg = "#8e9292", }, -- Comment        xxx ctermfg=244 guifg=#8e9292
    Conceal { bg = "darkgrey", fg = "lightgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    Conditional { gui = "bold", fg = "#c57825", }, -- Conditional    xxx ctermfg=172 gui=bold guifg=#c57825
    Constant { gui = "bold", fg = "#9676ac", }, -- Constant       xxx ctermfg=103 gui=bold guifg=#9676ac
    CopilotSuggestion { fg = "#808080", }, -- CopilotSuggestion xxx ctermfg=244 guifg=#808080
    CtrlPMatch { bg = "#214283", fg = "#a9b7c6", }, -- CtrlPMatch     xxx ctermfg=188 ctermbg=24 guifg=#a9b7c6 guibg=#214283
    Cursor { bg = "#a9b7c6", fg = "#2b2b2b", }, -- Cursor         xxx ctermfg=188 ctermbg=250 guifg=#2b2b2b guibg=#a9b7c6
    CursorColumn { bg = "#313335", }, -- CursorColumn   xxx ctermbg=236 guibg=#313335
    CursorLine { bg = "#323232", }, -- CursorLine     xxx ctermbg=236 guibg=#323232
    CursorLineFold { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    CursorLineNr { bg = "#214283", }, -- CursorLineNr   xxx ctermbg=24 guibg=#214283
    CursorLineSign { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Debug { Special }, -- Debug          xxx links to Special
    Define { gui = "bold", fg = "#c57825", }, -- Define         xxx ctermfg=172 gui=bold guifg=#c57825
    Delimiter { Special }, -- Delimiter      xxx links to Special
    DevIconAi { fg = "#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconAwk { fg = "#4d5a5e", }, -- DevIconAwk     xxx ctermfg=59 guifg=#4d5a5e
    DevIconBabelrc { fg = "#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconBash { fg = "#89e051", }, -- DevIconBash    xxx ctermfg=113 guifg=#89e051
    DevIconBashProfile { fg = "#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconBashrc { fg = "#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconBat { fg = "#c1f12e", }, -- DevIconBat     xxx ctermfg=154 guifg=#c1f12e
    DevIconBinaryGLTF { fg = "#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=215 guifg=#ffb13b
    DevIconBmp { fg = "#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconBrewfile { fg = "#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconC { fg = "#599eff", }, -- DevIconC       xxx ctermfg=75 guifg=#599eff
    DevIconCMake { fg = "#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconCMakeLists { fg = "#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconCPlusPlus { fg = "#f34b7d", }, -- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
    DevIconClojure { fg = "#8dc149", }, -- DevIconClojure xxx ctermfg=107 guifg=#8dc149
    DevIconClojureC { fg = "#8dc149", }, -- DevIconClojureC xxx ctermfg=107 guifg=#8dc149
    DevIconClojureDart { fg = "#519aba", }, -- DevIconClojureDart xxx ctermfg=67 guifg=#519aba
    DevIconClojureJS { fg = "#519aba", }, -- DevIconClojureJS xxx ctermfg=67 guifg=#519aba
    DevIconCobol { fg = "#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconCoffee { fg = "#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconConf { fg = "#6d8086", }, -- DevIconConf    xxx ctermfg=66 guifg=#6d8086
    DevIconConfigRu { fg = "#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconConfiguration { fg = "#ececec", }, -- DevIconConfiguration xxx ctermfg=231 guifg=#ececec
    DevIconCp { fg = "#519aba", }, -- DevIconCp      xxx ctermfg=67 guifg=#519aba
    DevIconCpp { fg = "#519aba", }, -- DevIconCpp     xxx ctermfg=67 guifg=#519aba
    DevIconCrystal { fg = "#000000", }, -- DevIconCrystal xxx ctermfg=16 guifg=#000000
    DevIconCs { fg = "#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconCsh { fg = "#4d5a5e", }, -- DevIconCsh     xxx ctermfg=59 guifg=#4d5a5e
    DevIconCson { fg = "#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconCss { fg = "#42a5f5", }, -- DevIconCss     xxx ctermfg=39 guifg=#42a5f5
    DevIconCsv { fg = "#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconCxx { fg = "#519aba", }, -- DevIconCxx     xxx ctermfg=67 guifg=#519aba
    DevIconD { fg = "#427819", }, -- DevIconD       xxx ctermfg=64 guifg=#427819
    DevIconDart { fg = "#03589c", }, -- DevIconDart    xxx ctermfg=25 guifg=#03589c
    DevIconDb { fg = "#dad8d8", }, -- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
    DevIconDefault { fg = "#6d8086", }, -- DevIconDefault xxx ctermfg=66 guifg=#6d8086
    DevIconDesktopEntry { fg = "#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=60 guifg=#563d7c
    DevIconDiff { fg = "#41535b", }, -- DevIconDiff    xxx ctermfg=59 guifg=#41535b
    DevIconDoc { fg = "#185abd", }, -- DevIconDoc     xxx ctermfg=25 guifg=#185abd
    DevIconDockerfile { fg = "#384d54", }, -- DevIconDockerfile xxx ctermfg=59 guifg=#384d54
    DevIconDrools { fg = "#ffafaf", }, -- DevIconDrools  xxx ctermfg=217 guifg=#ffafaf
    DevIconDropbox { fg = "#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061fe
    DevIconDsStore { fg = "#41535b", }, -- DevIconDsStore xxx ctermfg=59 guifg=#41535b
    DevIconDump { fg = "#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconEdn { fg = "#519aba", }, -- DevIconEdn     xxx ctermfg=67 guifg=#519aba
    DevIconEex { fg = "#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconEjs { fg = "#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconElm { fg = "#519aba", }, -- DevIconElm     xxx ctermfg=67 guifg=#519aba
    DevIconEnv { fg = "#faf743", }, -- DevIconEnv     xxx ctermfg=226 guifg=#faf743
    DevIconEpp { fg = "#ffa61a", }, -- DevIconEpp     xxx guifg=#ffa61a
    DevIconErb { fg = "#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconErl { fg = "#b83998", }, -- DevIconErl     xxx ctermfg=132 guifg=#b83998
    DevIconEx { fg = "#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconExs { fg = "#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconFavicon { fg = "#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconFennel { fg = "#fff3d7", }, -- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
    DevIconFish { fg = "#4d5a5e", }, -- DevIconFish    xxx ctermfg=59 guifg=#4d5a5e
    DevIconFs { fg = "#519aba", }, -- DevIconFs      xxx ctermfg=67 guifg=#519aba
    DevIconFsharp { fg = "#519aba", }, -- DevIconFsharp  xxx ctermfg=67 guifg=#519aba
    DevIconFsi { fg = "#519aba", }, -- DevIconFsi     xxx ctermfg=67 guifg=#519aba
    DevIconFsscript { fg = "#519aba", }, -- DevIconFsscript xxx ctermfg=67 guifg=#519aba
    DevIconFsx { fg = "#519aba", }, -- DevIconFsx     xxx ctermfg=67 guifg=#519aba
    DevIconGDScript { fg = "#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconGemfile { fg = "#701516", }, -- DevIconGemfile xxx ctermfg=52 guifg=#701516
    DevIconGemspec { fg = "#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconGif { fg = "#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconGitAttributes { fg = "#41535b", }, -- DevIconGitAttributes xxx ctermfg=59 guifg=#41535b
    DevIconGitCommit { fg = "#41535b", }, -- DevIconGitCommit xxx ctermfg=59 guifg=#41535b
    DevIconGitConfig { fg = "#41535b", }, -- DevIconGitConfig xxx ctermfg=59 guifg=#41535b
    DevIconGitIgnore { fg = "#41535b", }, -- DevIconGitIgnore xxx ctermfg=59 guifg=#41535b
    DevIconGitLogo { fg = "#f14c28", }, -- DevIconGitLogo xxx ctermfg=202 guifg=#f14c28
    DevIconGitModules { fg = "#41535b", }, -- DevIconGitModules xxx ctermfg=59 guifg=#41535b
    DevIconGitlabCI { fg = "#e24329", }, -- DevIconGitlabCI xxx ctermfg=166 guifg=#e24329
    DevIconGo { fg = "#519aba", }, -- DevIconGo      xxx ctermfg=67 guifg=#519aba
    DevIconGodotProject { fg = "#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconGruntfile { fg = "#e37933", }, -- DevIconGruntfile xxx ctermfg=173 guifg=#e37933
    DevIconGulpfile { fg = "#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
    DevIconGvimrc { fg = "#019833", }, -- DevIconGvimrc  xxx ctermfg=29 guifg=#019833
    DevIconH { fg = "#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconHaml { fg = "#eaeae1", }, -- DevIconHaml    xxx ctermfg=188 guifg=#eaeae1
    DevIconHbs { fg = "#f0772b", }, -- DevIconHbs     xxx ctermfg=208 guifg=#f0772b
    DevIconHeex { fg = "#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconHh { fg = "#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconHpp { fg = "#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconHrl { fg = "#b83998", }, -- DevIconHrl     xxx ctermfg=132 guifg=#b83998
    DevIconHs { fg = "#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconHtm { fg = "#e34c26", }, -- DevIconHtm     xxx ctermfg=166 guifg=#e34c26
    DevIconHtml { fg = "#e44d26", }, -- DevIconHtml    xxx ctermfg=202 guifg=#e44d26
    DevIconHxx { fg = "#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
    DevIconIco { fg = "#cbcb41", }, -- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
    DevIconImportConfiguration { fg = "#ececec", }, -- DevIconImportConfiguration xxx ctermfg=231 guifg=#ececec
    DevIconIni { fg = "#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconJava { fg = "#cc3e44", }, -- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
    DevIconJl { fg = "#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconJpeg { fg = "#a074c4", }, -- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
    DevIconJpg { fg = "#a074c4", }, -- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
    DevIconJs { fg = "#cbcb41", }, -- DevIconJs      xxx ctermfg=185 guifg=#cbcb41
    DevIconJson { fg = "#cbcb41", }, -- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
    DevIconJsx { fg = "#519aba", }, -- DevIconJsx     xxx ctermfg=67 guifg=#519aba
    DevIconKotlin { fg = "#f88a02", }, -- DevIconKotlin  xxx ctermfg=208 guifg=#f88a02
    DevIconKotlinScript { fg = "#f88a02", }, -- DevIconKotlinScript xxx ctermfg=208 guifg=#f88a02
    DevIconKsh { fg = "#4d5a5e", }, -- DevIconKsh     xxx ctermfg=59 guifg=#4d5a5e
    DevIconLeex { fg = "#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconLess { fg = "#563d7c", }, -- DevIconLess    xxx ctermfg=60 guifg=#563d7c
    DevIconLhs { fg = "#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconLicense { fg = "#cbcb41", }, -- DevIconLicense xxx ctermfg=185 guifg=#cbcb41
    DevIconLock { fg = "#bbbbbb", }, -- DevIconLock    xxx ctermfg=250 guifg=#bbbbbb
    DevIconLog { fg = "#ffffff", }, -- DevIconLog     xxx ctermfg=15 guifg=#ffffff
    DevIconLua { fg = "#51a0cf", }, -- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
    DevIconMakefile { fg = "#6d8086", }, -- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
    DevIconMarkdown { fg = "#519aba", }, -- DevIconMarkdown xxx ctermfg=67 guifg=#519aba
    DevIconMaterial { fg = "#b83998", }, -- DevIconMaterial xxx ctermfg=132 guifg=#b83998
    DevIconMd { fg = "#ffffff", }, -- DevIconMd      xxx ctermfg=15 guifg=#ffffff
    DevIconMdx { fg = "#519aba", }, -- DevIconMdx     xxx ctermfg=67 guifg=#519aba
    DevIconMint { fg = "#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconMixLock { fg = "#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconMjs { fg = "#f1e05a", }, -- DevIconMjs     xxx ctermfg=221 guifg=#f1e05a
    DevIconMl { fg = "#e37933", }, -- DevIconMl      xxx ctermfg=173 guifg=#e37933
    DevIconMli { fg = "#e37933", }, -- DevIconMli     xxx ctermfg=173 guifg=#e37933
    DevIconMotoko { fg = "#9772fb", }, -- DevIconMotoko  xxx ctermfg=99 guifg=#9772fb
    DevIconMustache { fg = "#e37933", }, -- DevIconMustache xxx ctermfg=173 guifg=#e37933
    DevIconNPMIgnore { fg = "#e8274b", }, -- DevIconNPMIgnore xxx ctermfg=161 guifg=#e8274b
    DevIconNPMrc { fg = "#e8274b", }, -- DevIconNPMrc   xxx ctermfg=161 guifg=#e8274b
    DevIconNim { fg = "#f3d400", }, -- DevIconNim     xxx ctermfg=220 guifg=#f3d400
    DevIconNix { fg = "#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconNodeModules { fg = "#e8274b", }, -- DevIconNodeModules xxx ctermfg=161 guifg=#e8274b
    DevIconOPUS { fg = "#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#f88a02
    DevIconOpenTypeFont { fg = "#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=231 guifg=#ececec
    DevIconPackageJson { fg = "#e8274b", }, -- DevIconPackageJson xxx guifg=#e8274b
    DevIconPackageLockJson { fg = "#7a0d21", }, -- DevIconPackageLockJson xxx guifg=#7a0d21
    DevIconPackedResource { fg = "#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconPdf { fg = "#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconPhp { fg = "#a074c4", }, -- DevIconPhp     xxx ctermfg=140 guifg=#a074c4
    DevIconPl { fg = "#519aba", }, -- DevIconPl      xxx ctermfg=67 guifg=#519aba
    DevIconPm { fg = "#519aba", }, -- DevIconPm      xxx ctermfg=67 guifg=#519aba
    DevIconPng { fg = "#a074c4", }, -- DevIconPng     xxx ctermfg=140 guifg=#a074c4
    DevIconPp { fg = "#ffa61a", }, -- DevIconPp      xxx guifg=#ffa61a
    DevIconPpt { fg = "#cb4a32", }, -- DevIconPpt     xxx ctermfg=167 guifg=#cb4a32
    DevIconPrisma { fg = "#ffffff", }, -- DevIconPrisma  xxx ctermfg=15 guifg=#ffffff
    DevIconProcfile { fg = "#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconProlog { fg = "#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconPromptPs1 { fg = "#4d5a5e", }, -- DevIconPromptPs1 xxx ctermfg=59 guifg=#4d5a5e
    DevIconPsb { fg = "#519aba", }, -- DevIconPsb     xxx ctermfg=67 guifg=#519aba
    DevIconPsd { fg = "#519aba", }, -- DevIconPsd     xxx ctermfg=67 guifg=#519aba
    DevIconPy { fg = "#ffbc03", }, -- DevIconPy      xxx ctermfg=61 guifg=#ffbc03
    DevIconPyc { fg = "#ffe291", }, -- DevIconPyc     xxx ctermfg=67 guifg=#ffe291
    DevIconPyd { fg = "#ffe291", }, -- DevIconPyd     xxx ctermfg=67 guifg=#ffe291
    DevIconPyo { fg = "#ffe291", }, -- DevIconPyo     xxx ctermfg=67 guifg=#ffe291
    DevIconR { fg = "#358a5b", }, -- DevIconR       xxx ctermfg=65 guifg=#358a5b
    DevIconRake { fg = "#701516", }, -- DevIconRake    xxx ctermfg=52 guifg=#701516
    DevIconRakefile { fg = "#701516", }, -- DevIconRakefile xxx ctermfg=52 guifg=#701516
    DevIconRb { fg = "#701516", }, -- DevIconRb      xxx ctermfg=52 guifg=#701516
    DevIconRlib { fg = "#dea584", }, -- DevIconRlib    xxx ctermfg=180 guifg=#dea584
    DevIconRmd { fg = "#519aba", }, -- DevIconRmd     xxx ctermfg=67 guifg=#519aba
    DevIconRproj { fg = "#358a5b", }, -- DevIconRproj   xxx ctermfg=65 guifg=#358a5b
    DevIconRs { fg = "#dea584", }, -- DevIconRs      xxx ctermfg=180 guifg=#dea584
    DevIconRss { fg = "#fb9d3b", }, -- DevIconRss     xxx ctermfg=215 guifg=#fb9d3b
    DevIconSass { fg = "#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconScala { fg = "#cc3e44", }, -- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
    DevIconScss { fg = "#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconSettingsJson { fg = "#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854cc7
    DevIconSh { fg = "#4d5a5e", }, -- DevIconSh      xxx ctermfg=59 guifg=#4d5a5e
    DevIconSig { fg = "#e37933", }, -- DevIconSig     xxx ctermfg=173 guifg=#e37933
    DevIconSlim { fg = "#e34c26", }, -- DevIconSlim    xxx ctermfg=166 guifg=#e34c26
    DevIconSln { fg = "#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854cc7
    DevIconSml { fg = "#e37933", }, -- DevIconSml     xxx ctermfg=173 guifg=#e37933
    DevIconSolidity { fg = "#519aba", }, -- DevIconSolidity xxx ctermfg=67 guifg=#519aba
    DevIconSql { fg = "#dad8d8", }, -- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
    DevIconStyl { fg = "#8dc149", }, -- DevIconStyl    xxx ctermfg=107 guifg=#8dc149
    DevIconSuo { fg = "#e37933", }, -- DevIconSuo     xxx ctermfg=98 guifg=#e37933
    DevIconSvelte { fg = "#ff3e00", }, -- DevIconSvelte  xxx ctermfg=202 guifg=#ff3e00
    DevIconSvg { fg = "#ffb13b", }, -- DevIconSvg     xxx ctermfg=215 guifg=#ffb13b
    DevIconSwift { fg = "#e37933", }, -- DevIconSwift   xxx ctermfg=173 guifg=#e37933
    DevIconSystemVerilog { fg = "#019833", }, -- DevIconSystemVerilog xxx ctermfg=29 guifg=#019833
    DevIconTcl { fg = "#1e5cb3", }, -- DevIconTcl     xxx ctermfg=67 guifg=#1e5cb3
    DevIconTerminal { fg = "#31b53e", }, -- DevIconTerminal xxx ctermfg=71 guifg=#31b53e
    DevIconTex { fg = "#3d6117", }, -- DevIconTex     xxx ctermfg=58 guifg=#3d6117
    DevIconTextResource { fg = "#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconTextScene { fg = "#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconToml { fg = "#6d8086", }, -- DevIconToml    xxx ctermfg=66 guifg=#6d8086
    DevIconTor { fg = "#519aba", }, -- DevIconTor     xxx ctermfg=67 guifg=#519aba
    DevIconTs { fg = "#519aba", }, -- DevIconTs      xxx ctermfg=67 guifg=#519aba
    DevIconTsx { fg = "#519aba", }, -- DevIconTsx     xxx ctermfg=67 guifg=#519aba
    DevIconTwig { fg = "#8dc149", }, -- DevIconTwig    xxx ctermfg=107 guifg=#8dc149
    DevIconTxt { fg = "#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconVHDL { fg = "#019833", }, -- DevIconVHDL    xxx ctermfg=29 guifg=#019833
    DevIconVagrantfile { fg = "#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563ff
    DevIconVerilog { fg = "#019833", }, -- DevIconVerilog xxx ctermfg=29 guifg=#019833
    DevIconVim { fg = "#019833", }, -- DevIconVim     xxx ctermfg=29 guifg=#019833
    DevIconVimrc { fg = "#019833", }, -- DevIconVimrc   xxx ctermfg=29 guifg=#019833
    DevIconVue { fg = "#8dc149", }, -- DevIconVue     xxx ctermfg=107 guifg=#8dc149
    DevIconWebmanifest { fg = "#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=221 guifg=#f1e05a
    DevIconWebp { fg = "#a074c4", }, -- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
    DevIconWebpack { fg = "#519aba", }, -- DevIconWebpack xxx ctermfg=67 guifg=#519aba
    DevIconXcPlayground { fg = "#e37933", }, -- DevIconXcPlayground xxx ctermfg=173 guifg=#e37933
    DevIconXls { fg = "#207245", }, -- DevIconXls     xxx ctermfg=23 guifg=#207245
    DevIconXml { fg = "#e37933", }, -- DevIconXml     xxx ctermfg=173 guifg=#e37933
    DevIconXul { fg = "#e37933", }, -- DevIconXul     xxx ctermfg=173 guifg=#e37933
    DevIconYaml { fg = "#6d8086", }, -- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
    DevIconYml { fg = "#6d8086", }, -- DevIconYml     xxx ctermfg=66 guifg=#6d8086
    DevIconZig { fg = "#f69a1b", }, -- DevIconZig     xxx ctermfg=208 guifg=#f69a1b
    DevIconZsh { fg = "#89e051", }, -- DevIconZsh     xxx ctermfg=113 guifg=#89e051
    DevIconZshenv { fg = "#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconZshprofile { fg = "#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconZshrc { fg = "#89e051", }, -- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
    DiagnosticError { fg = "red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticFloatingError { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticFloatingHint { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticFloatingInfo { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticFloatingWarn { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticHint { fg = "lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticInfo { fg = "lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticSignError { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    DiagnosticSignHint { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    DiagnosticSignInfo { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    DiagnosticSignWarn { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    DiagnosticUnderlineError { gui = "underline", sp = "red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineHint { gui = "underline", sp = "lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineInfo { gui = "underline", sp = "lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineWarn { gui = "underline", sp = "orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticVirtualTextError { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticVirtualTextHint { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticVirtualTextInfo { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticVirtualTextWarn { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticWarn { fg = "orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiffAdd { bg = "#365546", gui = "bold", fg = "#a9b7c6", }, -- DiffAdd        xxx cterm=bold ctermfg=188 ctermbg=64 gui=bold guifg=#a9b7c6 guibg=#365546
    DiffChange { bg = "#263b59", fg = "#a9b7c6", }, -- DiffChange     xxx ctermfg=188 ctermbg=23 guifg=#a9b7c6 guibg=#263b59
    DiffDelete { fg = "#8c0909", }, -- DiffDelete     xxx ctermfg=88 guifg=#8c0909
    DiffText { bg = "#204a87", gui = "bold", fg = "#a9b7c6", }, -- DiffText       xxx cterm=bold ctermfg=188 ctermbg=24 gui=bold guifg=#a9b7c6 guibg=#204a87
    Directory { gui = "italic", fg = "#9676ac", }, -- Directory      xxx ctermfg=103 gui=italic guifg=#9676ac
    EndOfBuffer { NonText }, -- EndOfBuffer    xxx links to NonText
    Error { bg = "red", fg = "white", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
    ErrorMsg { bg = "#990000", fg = "#ffffff", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=88 guifg=#ffffff guibg=#990000
    Exception { Statement }, -- Exception      xxx links to Statement
    ExtraWhitespace { bg = "#ff0000", }, -- ExtraWhitespace xxx ctermbg=9 guibg=#ff0000
    Float { fg = "#7ca8c6", }, -- Float          xxx ctermfg=67 guifg=#7ca8c6
    FloatShadow { bg = "black", blend = 80, }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough { bg = "black", blend = 100, }, -- FloatShadowThrough xxx guibg=Black blend=100
    FoldColumn { bg = "grey", fg = "cyan", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
    Folded { bg = "#2b2b2b", fg = "#8e9292", }, -- Folded         xxx ctermfg=244 ctermbg=235 guifg=#8e9292 guibg=#2b2b2b
    Function { gui = "bold", fg = "#c57825", }, -- Function       xxx cterm=bold ctermfg=221 gui=bold guifg=#c57825
    Identifier { fg = "#c57825", }, -- Identifier     xxx ctermfg=222 guifg=#c57825
    Ignore { fg = "bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    IncSearch { bg = "#b1c73d", fg = "#323232", }, -- IncSearch      xxx cterm=reverse ctermfg=188 ctermbg=24 guifg=#323232 guibg=#b1c73d
    Include { PreProc }, -- Include        xxx links to PreProc
    Keyword { gui = "bold", fg = "#c57825", }, -- Keyword        xxx ctermfg=172 gui=bold guifg=#c57825
    Label { fg = "#9676ac", }, -- Label          xxx ctermfg=103 guifg=#9676ac
    LineNr { bg = "#323232", fg = "#888888", }, -- LineNr         xxx ctermfg=60 ctermbg=236 guifg=#888888 guibg=#323232
    LineNrAbove { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow { LineNr }, -- LineNrBelow    xxx links to LineNr
    LspReferenceText { CursorLine }, -- LspReferenceText xxx links to CursorLine
    Macro { PreProc }, -- Macro          xxx links to PreProc
    MatchParen { gui = "underline", fg = "#c57825", }, -- MatchParen     xxx cterm=underline ctermfg=173 gui=underline guifg=#c57825
    ModeMsg { gui = "bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    MoreMsg { gui = "bold", fg = "seagreen", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    MsgSeparator { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    NERDTreeBookmark { Normal }, -- NERDTreeBookmark xxx links to Normal
    NERDTreeBookmarkName { Identifier }, -- NERDTreeBookmarkName xxx links to Identifier
    NERDTreeBookmarksHeader { Statement }, -- NERDTreeBookmarksHeader xxx links to Statement
    NERDTreeBookmarksLeader { Ignore }, -- NERDTreeBookmarksLeader xxx links to Ignore
    NERDTreeCWD { Statement }, -- NERDTreeCWD    xxx links to Statement
    NERDTreeClosable { Directory }, -- NERDTreeClosable xxx links to Directory
    NERDTreeCurrentNode { Search }, -- NERDTreeCurrentNode xxx links to Search
    NERDTreeDir { Directory }, -- NERDTreeDir    xxx links to Directory
    NERDTreeDirSlash { Identifier }, -- NERDTreeDirSlash xxx links to Identifier
    NERDTreeExecFile { Title }, -- NERDTreeExecFile xxx links to Title
    NERDTreeFlags { Number }, -- NERDTreeFlags  xxx links to Number
    NERDTreeGitStatusDeleted { fg = "#a9b7c6", }, -- NERDTreeGitStatusDeleted xxx ctermfg=250 guifg=#a9b7c6
    NERDTreeGitStatusIgnored { fg = "#bfbfbf", }, -- NERDTreeGitStatusIgnored xxx ctermfg=250 guifg=#bfbfbf
    NERDTreeGitStatusModified { fg = "#c57825", }, -- NERDTreeGitStatusModified xxx ctermfg=172 guifg=#c57825
    NERDTreeGitStatusRenamed { fg = "#a9b7c6", }, -- NERDTreeGitStatusRenamed xxx ctermfg=159 guifg=#a9b7c6
    NERDTreeGitStatusStaged { fg = "#c57825", }, -- NERDTreeGitStatusStaged xxx ctermfg=221 guifg=#c57825
    NERDTreeGitStatusUnmerged { fg = "#9676ac", }, -- NERDTreeGitStatusUnmerged xxx ctermfg=103 guifg=#9676ac
    NERDTreeGitStatusUntracked { fg = "#8e9292", }, -- NERDTreeGitStatusUntracked xxx ctermfg=244 guifg=#8e9292
    NERDTreeHelp { String }, -- NERDTreeHelp   xxx links to String
    NERDTreeHelpCommand { Identifier }, -- NERDTreeHelpCommand xxx links to Identifier
    NERDTreeHelpKey { Identifier }, -- NERDTreeHelpKey xxx links to Identifier
    NERDTreeIgnore { Ignore }, -- NERDTreeIgnore xxx links to Ignore
    NERDTreeLinkTarget { Type }, -- NERDTreeLinkTarget xxx links to Type
    NERDTreeOpenable { Directory }, -- NERDTreeOpenable xxx links to Directory
    NERDTreePart { Special }, -- NERDTreePart   xxx links to Special
    NERDTreePartFile { Type }, -- NERDTreePartFile xxx links to Type
    NERDTreeRO { WarningMsg }, -- NERDTreeRO     xxx links to WarningMsg
    NERDTreeToggleOff { WarningMsg }, -- NERDTreeToggleOff xxx links to WarningMsg
    NERDTreeToggleOn { Question }, -- NERDTreeToggleOn xxx links to Question
    NERDTreeUp { Directory }, -- NERDTreeUp     xxx links to Directory
    NonText { fg = "#8e9292", }, -- NonText        xxx ctermfg=244 guifg=#8e9292
    Normal { bg = "#2b2b2b", fg = "#a9b7c6", }, -- Normal         xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    NormalFloat { Pmenu }, -- NormalFloat    xxx links to Pmenu
    Number { fg = "#7ca8c6", }, -- Number         xxx ctermfg=67 guifg=#7ca8c6
    NvimAssignment { Operator }, -- NvimAssignment xxx links to Operator
    NvimFigureBrace { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimIdentifier { Identifier }, -- NvimIdentifier xxx links to Identifier
    NvimInternalError { bg = "red", fg = "red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimInvalid { Error }, -- NvimInvalid    xxx links to Error
    NvimInvalidSingleQuotedUnknownEscape { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSpacing { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    NvimNumber { Number }, -- NvimNumber     xxx links to Number
    NvimNumberPrefix { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOperator { Operator }, -- NvimOperator   xxx links to Operator
    NvimOptionSigil { Type }, -- NvimOptionSigil xxx links to Type
    NvimSingleQuotedUnknownEscape { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimSpacing { Normal }, -- NvimSpacing    xxx links to Normal
    NvimString { String }, -- NvimString     xxx links to String
    Operator { fg = "#a9b7c6", }, -- Operator       xxx ctermfg=250 guifg=#a9b7c6
    Pmenu { bg = "#323232", }, -- Pmenu          xxx ctermbg=238 guibg=#323232
    PmenuSbar { bg = "#8e9292", }, -- PmenuSbar      xxx ctermbg=24 guibg=#8e9292
    PmenuSel { bg = "#214283", }, -- PmenuSel       xxx ctermfg=188 ctermbg=24 guibg=#214283
    PmenuThumb {}, -- PmenuThumb     xxx ctermfg=59
    PreCondit { PreProc }, -- PreCondit      xxx links to PreProc
    PreProc { gui = "bold", fg = "#c57825", }, -- PreProc        xxx ctermfg=172 gui=bold guifg=#c57825
    Question { gui = "bold", fg = "green", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    QuickFixLine { Search }, -- QuickFixLine   xxx links to Search
    RedrawDebugClear { bg = "yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed { bg = "green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugNormal { gui = "reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugRecompose { bg = "red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Repeat { Statement }, -- Repeat         xxx links to Statement
    Search { bg = "#214283", fg = "#a9b7c6", }, -- Search         xxx ctermfg=188 ctermbg=24 guifg=#a9b7c6 guibg=#214283
    SignColumn { bg = "#323232", fg = "#888888", }, -- SignColumn     xxx ctermfg=60 ctermbg=236 guifg=#888888 guibg=#323232
    Special { gui = "bold", fg = "#c57825", }, -- Special        xxx ctermfg=172 gui=bold guifg=#c57825
    SpecialChar { Special }, -- SpecialChar    xxx links to Special
    SpecialComment { Special }, -- SpecialComment xxx links to Special
    SpecialKey { bg = "#313335", fg = "#bfbfbf", }, -- SpecialKey     xxx ctermfg=250 ctermbg=236 guifg=#bfbfbf guibg=#313335
    SpellBad { gui = "undercurl", fg = "#aeae80", }, -- SpellBad       xxx cterm=undercurl ctermfg=150 gui=undercurl guifg=#aeae80
    SpellCap { gui = "undercurl", fg = "#aeae80", }, -- SpellCap       xxx cterm=undercurl ctermfg=150 gui=undercurl guifg=#aeae80
    SpellLocal { gui = "undercurl", fg = "#aeae80", }, -- SpellLocal     xxx cterm=undercurl ctermfg=150 gui=undercurl guifg=#aeae80
    SpellRare { gui = "undercurl", fg = "#aeae80", }, -- SpellRare      xxx cterm=undercurl ctermfg=150 gui=undercurl guifg=#aeae80
    Statement { fg = "#c57825", }, -- Statement      xxx ctermfg=172 guifg=#c57825
    StatusLine { bg = "#323232", gui = "bold", fg = "#a9b7c6", }, -- StatusLine     xxx cterm=bold ctermfg=67 ctermbg=236 gui=bold guifg=#a9b7c6 guibg=#323232
    StatusLineNC { bg = "#323232", fg = "#a9b7c6", }, -- StatusLineNC   xxx ctermfg=188 ctermbg=236 guifg=#a9b7c6 guibg=#323232
    StorageClass { gui = "bold", fg = "#c57825", }, -- StorageClass   xxx ctermfg=172 gui=bold guifg=#c57825
    String { fg = "#5e8759", }, -- String         xxx ctermfg=65 guifg=#5e8759
    Structure { Type }, -- Structure      xxx links to Type
    Substitute { Search }, -- Substitute     xxx links to Search
    TSAnnotation { PreProc }, -- TSAnnotation   xxx links to PreProc
    TSAttribute { PreProc }, -- TSAttribute    xxx links to PreProc
    TSBoolean { Boolean }, -- TSBoolean      xxx links to Boolean
    TSCharacter { Character }, -- TSCharacter    xxx links to Character
    TSComment { Comment }, -- TSComment      xxx links to Comment
    TSConditional { Conditional }, -- TSConditional  xxx links to Conditional
    TSConstBuiltin { Special }, -- TSConstBuiltin xxx links to Special
    TSConstMacro { Define }, -- TSConstMacro   xxx links to Define
    TSConstant { Constant }, -- TSConstant     xxx links to Constant
    TSConstructor { Special }, -- TSConstructor  xxx links to Special
    TSDanger { WarningMsg }, -- TSDanger       xxx links to WarningMsg
    TSDefine { Define }, -- TSDefine       xxx links to Define
    TSEmphasis { gui = "italic", }, -- TSEmphasis     xxx cterm=italic gui=italic
    TSEnvironmentName { Type }, -- TSEnvironmentName xxx links to Type
    TSField { Identifier }, -- TSField        xxx links to Identifier
    TSFloat { Float }, -- TSFloat        xxx links to Float
    TSFuncBuiltin { Special }, -- TSFuncBuiltin  xxx links to Special
    TSFunction { Function }, -- TSFunction     xxx links to Function
    TSKeyword { Keyword }, -- TSKeyword      xxx links to Keyword
    TSKeywordFunction { Keyword }, -- TSKeywordFunction xxx links to Keyword
    TSLabel { Label }, -- TSLabel        xxx links to Label
    TSLiteral { String }, -- TSLiteral      xxx links to String
    TSMath { Special }, -- TSMath         xxx links to Special
    TSMethod { Function }, -- TSMethod       xxx links to Function
    TSNone {}, -- TSNone         xxx cterm= gui=
    TSNumber { Number }, -- TSNumber       xxx links to Number
    TSOperator { Operator }, -- TSOperator     xxx links to Operator
    TSParameter { Identifier }, -- TSParameter    xxx links to Identifier
    TSPreProc { PreProc }, -- TSPreProc      xxx links to PreProc
    TSProperty { Identifier }, -- TSProperty     xxx links to Identifier
    TSStorageClass { StorageClass }, -- TSStorageClass xxx links to StorageClass
    TSStrike { gui = "strikethrough", }, -- TSStrike       xxx cterm=strikethrough gui=strikethrough
    TSString { String }, -- TSString       xxx links to String
    TSStringRegex { String }, -- TSStringRegex  xxx links to String
    TSStrong { gui = "bold", }, -- TSStrong       xxx cterm=bold gui=bold
    TSSymbol { Identifier }, -- TSSymbol       xxx links to Identifier
    TSTag { Label }, -- TSTag          xxx links to Label
    TSText { TSNone }, -- TSText         xxx links to TSNone
    TSTextReference { Constant }, -- TSTextReference xxx links to Constant
    TSTitle { Title }, -- TSTitle        xxx links to Title
    TSTodo { Todo }, -- TSTodo         xxx links to Todo
    TSType { Type }, -- TSType         xxx links to Type
    TSTypeBuiltin { Type }, -- TSTypeBuiltin  xxx links to Type
    TSTypeQualifier { Type }, -- TSTypeQualifier xxx links to Type
    TSURI { Underlined }, -- TSURI          xxx links to Underlined
    TSUnderline { gui = "underline", }, -- TSUnderline    xxx cterm=underline gui=underline
    TSVariableBuiltin { Special }, -- TSVariableBuiltin xxx links to Special
    TSWarning { Todo }, -- TSWarning      xxx links to Todo
    TabLine { bg = "#2b2b2b", fg = "#a9b7c6", }, -- TabLine        xxx ctermfg=146 ctermbg=16 guifg=#a9b7c6 guibg=#2b2b2b
    TabLineFill { bg = "#2b2b2b", fg = "#a9b7c6", }, -- TabLineFill    xxx ctermfg=146 ctermbg=16 guifg=#a9b7c6 guibg=#2b2b2b
    TabLineSel { bg = "#515658", fg = "#a9b7c6", }, -- TabLineSel     xxx ctermfg=146 ctermbg=59 guifg=#a9b7c6 guibg=#515658
    TelescopeMatching { Special }, -- TelescopeMatching xxx links to Special
    TelescopeMultiIcon { Identifier }, -- TelescopeMultiIcon xxx links to Identifier
    TelescopeMultiSelection { Type }, -- TelescopeMultiSelection xxx links to Type
    TelescopeNormal { Normal }, -- TelescopeNormal xxx links to Normal
    TelescopePreviewBlock { Constant }, -- TelescopePreviewBlock xxx links to Constant
    TelescopePreviewCharDev { Constant }, -- TelescopePreviewCharDev xxx links to Constant
    TelescopePreviewDate { Directory }, -- TelescopePreviewDate xxx links to Directory
    TelescopePreviewDirectory { Directory }, -- TelescopePreviewDirectory xxx links to Directory
    TelescopePreviewExecute { String }, -- TelescopePreviewExecute xxx links to String
    TelescopePreviewGroup { Constant }, -- TelescopePreviewGroup xxx links to Constant
    TelescopePreviewHyphen { NonText }, -- TelescopePreviewHyphen xxx links to NonText
    TelescopePreviewLine { Visual }, -- TelescopePreviewLine xxx links to Visual
    TelescopePreviewLink { Special }, -- TelescopePreviewLink xxx links to Special
    TelescopePreviewMatch { Search }, -- TelescopePreviewMatch xxx links to Search
    TelescopePreviewPipe { Constant }, -- TelescopePreviewPipe xxx links to Constant
    TelescopePreviewRead { Constant }, -- TelescopePreviewRead xxx links to Constant
    TelescopePreviewSize { String }, -- TelescopePreviewSize xxx links to String
    TelescopePreviewSocket { Statement }, -- TelescopePreviewSocket xxx links to Statement
    TelescopePreviewSticky { Keyword }, -- TelescopePreviewSticky xxx links to Keyword
    TelescopePreviewUser { Constant }, -- TelescopePreviewUser xxx links to Constant
    TelescopePreviewWrite { Statement }, -- TelescopePreviewWrite xxx links to Statement
    TelescopePromptCounter { NonText }, -- TelescopePromptCounter xxx links to NonText
    TelescopePromptPrefix { Identifier }, -- TelescopePromptPrefix xxx links to Identifier
    TelescopeResultsClass { Function }, -- TelescopeResultsClass xxx links to Function
    TelescopeResultsComment { Comment }, -- TelescopeResultsComment xxx links to Comment
    TelescopeResultsConstant { Constant }, -- TelescopeResultsConstant xxx links to Constant
    TelescopeResultsDiffAdd { DiffAdd }, -- TelescopeResultsDiffAdd xxx links to DiffAdd
    TelescopeResultsDiffChange { DiffChange }, -- TelescopeResultsDiffChange xxx links to DiffChange
    TelescopeResultsDiffDelete { DiffDelete }, -- TelescopeResultsDiffDelete xxx links to DiffDelete
    TelescopeResultsDiffUntracked { NonText }, -- TelescopeResultsDiffUntracked xxx links to NonText
    TelescopeResultsField { Function }, -- TelescopeResultsField xxx links to Function
    TelescopeResultsFileIcon { Normal }, -- TelescopeResultsFileIcon xxx links to Normal
    TelescopeResultsFunction { Function }, -- TelescopeResultsFunction xxx links to Function
    TelescopeResultsIdentifier { Identifier }, -- TelescopeResultsIdentifier xxx links to Identifier
    TelescopeResultsLineNr { LineNr }, -- TelescopeResultsLineNr xxx links to LineNr
    TelescopeResultsNumber { Number }, -- TelescopeResultsNumber xxx links to Number
    TelescopeResultsOperator { Operator }, -- TelescopeResultsOperator xxx links to Operator
    TelescopeSelection { Visual }, -- TelescopeSelection xxx links to Visual
    TermCursor { gui = "reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    Title { gui = "bold", fg = "#a9b7c6", }, -- Title          xxx cterm=bold ctermfg=159 gui=bold guifg=#a9b7c6
    Todo { gui = "bold,italic", fg = "#b1c73d", }, -- Todo           xxx ctermfg=148 gui=bold,italic guifg=#b1c73d
    Type { gui = "bold", fg = "#c57825", }, -- Type           xxx ctermfg=172 gui=bold guifg=#c57825
    Typedef { Type }, -- Typedef        xxx links to Type
    Underlined { gui = "underline", }, -- Underlined     xxx cterm=underline gui=underline
    VertSplit { bg = "#323232", fg = "#555555", }, -- VertSplit      xxx ctermfg=60 ctermbg=236 guifg=#555555 guibg=#323232
    Visual { bg = "#214283", }, -- Visual         xxx ctermbg=24 guibg=#214283
    WarningMsg { bg = "#990000", fg = "#ffffff", }, -- WarningMsg     xxx ctermfg=15 ctermbg=88 guifg=#ffffff guibg=#990000
    Whitespace { NonText }, -- Whitespace     xxx links to NonText
    WildMenu { bg = "yellow", fg = "black", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
    WinBar { gui = "bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC { WinBar }, -- WinBarNC       xxx links to WinBar
    WinSeparator { VertSplit }, -- WinSeparator   xxx links to VertSplit
    coffeeObjAssign { fg = "#d9c767", }, -- coffeeObjAssign xxx ctermfg=222 guifg=#d9c767
    coffeeObject { bg = "#2b2b2b", fg = "#a9b7c6", }, -- coffeeObject   xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    coffeeSpecialVar { bg = "#2b2b2b", fg = "#a9b7c6", }, -- coffeeSpecialVar xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    cssAtKeyword { PreProc }, -- cssAtKeyword   xxx links to PreProc
    cssAtRuleLogical { Statement }, -- cssAtRuleLogical xxx links to Statement
    cssAttr { Constant }, -- cssAttr        xxx links to Constant
    cssAttrComma { Special }, -- cssAttrComma   xxx links to Special
    cssAttributeSelector { String }, -- cssAttributeSelector xxx links to String
    cssBraceError { Error }, -- cssBraceError  xxx links to Error
    cssBraces { Function }, -- cssBraces      xxx links to Function
    cssClassName { fg = "#d0d0ff", }, -- cssClassName   xxx ctermfg=188 guifg=#d0d0ff
    cssClassNameDot { Function }, -- cssClassNameDot xxx links to Function
    cssColor { gui = "italic", fg = "#9676ac", }, -- cssColor       xxx ctermfg=103 gui=italic guifg=#9676ac
    cssComment { Comment }, -- cssComment     xxx links to Comment
    cssCommonAttr { gui = "bold", fg = "#06960e", }, -- cssCommonAttr  xxx cterm=bold ctermfg=28 gui=bold guifg=#06960e
    cssCustomProp { Special }, -- cssCustomProp  xxx links to Special
    cssDeprecated { Error }, -- cssDeprecated  xxx links to Error
    cssError { Error }, -- cssError       xxx links to Error
    cssFontDescriptor { Special }, -- cssFontDescriptor xxx links to Special
    cssFunction { Constant }, -- cssFunction    xxx links to Constant
    cssFunctionComma { Function }, -- cssFunctionComma xxx links to Function
    cssFunctionName { gui = "bold", fg = "#3c4c72", }, -- cssFunctionName xxx cterm=bold ctermfg=59 gui=bold guifg=#3c4c72
    cssHacks { Comment }, -- cssHacks       xxx links to Comment
    cssIdentifier { Function }, -- cssIdentifier  xxx links to Function
    cssImportant { Special }, -- cssImportant   xxx links to Special
    cssKeyFrameProp { Constant }, -- cssKeyFrameProp xxx links to Constant
    cssMediaComma { Normal }, -- cssMediaComma  xxx links to Normal
    cssMediaType { Special }, -- cssMediaType   xxx links to Special
    cssPagePseudo { PreProc }, -- cssPagePseudo  xxx links to PreProc
    cssProp { StorageClass }, -- cssProp        xxx links to StorageClass
    cssPseudoClassId { fg = "#d0d0ff", }, -- cssPseudoClassId xxx ctermfg=188 guifg=#d0d0ff
    cssPseudoClassLang { Constant }, -- cssPseudoClassLang xxx links to Constant
    cssSelectorOp { Special }, -- cssSelectorOp  xxx links to Special
    cssSelectorOp2 { Special }, -- cssSelectorOp2 xxx links to Special
    cssStringQ { String }, -- cssStringQ     xxx links to String
    cssStringQQ { String }, -- cssStringQQ    xxx links to String
    cssTagName { Statement }, -- cssTagName     xxx links to Statement
    cssURL { String }, -- cssURL         xxx links to String
    cssUnicodeEscape { Special }, -- cssUnicodeEscape xxx links to Special
    cssUnicodeRange { Constant }, -- cssUnicodeRange xxx links to Constant
    cssUnitDecorators { Number }, -- cssUnitDecorators xxx links to Number
    cssValueAngle { Number }, -- cssValueAngle  xxx links to Number
    cssValueFrequency { Number }, -- cssValueFrequency xxx links to Number
    cssValueInteger { Number }, -- cssValueInteger xxx links to Number
    cssValueLength { fg = "#7ca8c6", }, -- cssValueLength xxx ctermfg=67 guifg=#7ca8c6
    cssValueNumber { Number }, -- cssValueNumber xxx links to Number
    cssValueTime { Number }, -- cssValueTime   xxx links to Number
    cssVendor { Comment }, -- cssVendor      xxx links to Comment
    erubyComment { gui = "italic", fg = "#8e9292", }, -- erubyComment   xxx ctermfg=244 gui=italic guifg=#8e9292
    erubyDelimiter { PreProc }, -- erubyDelimiter xxx links to PreProc
    erubyRailsMethod { gui = "bold", fg = "#3c4c72", }, -- erubyRailsMethod xxx cterm=bold ctermfg=59 gui=bold guifg=#3c4c72
    go_icon {}, -- go_icon        xxx ctermfg=12
    haskell_icon {}, -- haskell_icon   xxx ctermfg=13
    hbs_icon {}, -- hbs_icon       xxx ctermfg=3
    heroku_icon {}, -- heroku_icon    xxx ctermfg=13
    htmlArg { fg = "#a9b7c6", }, -- htmlArg        xxx ctermfg=222 guifg=#a9b7c6
    htmlBold { gui = "bold", }, -- htmlBold       xxx cterm=bold gui=bold
    htmlBoldItalic { gui = "bold,italic", }, -- htmlBoldItalic xxx cterm=bold,italic gui=bold,italic
    htmlBoldItalicUnderline { htmlBoldUnderlineItalic }, -- htmlBoldItalicUnderline xxx links to htmlBoldUnderlineItalic
    htmlBoldUnderline { gui = "bold,underline", }, -- htmlBoldUnderline xxx cterm=bold,underline gui=bold,underline
    htmlBoldUnderlineItalic { gui = "bold,underline,italic", }, -- htmlBoldUnderlineItalic xxx cterm=bold,underline,italic gui=bold,underline,italic
    htmlComment { Comment }, -- htmlComment    xxx links to Comment
    htmlCssDefinition { Special }, -- htmlCssDefinition xxx links to Special
    htmlCssStyleComment { Comment }, -- htmlCssStyleComment xxx links to Comment
    htmlEndTag { fg = "#d9c767", }, -- htmlEndTag     xxx ctermfg=222 guifg=#d9c767
    htmlError { Error }, -- htmlError      xxx links to Error
    htmlH1 { Title }, -- htmlH1         xxx links to Title
    htmlHead { PreProc }, -- htmlHead       xxx links to PreProc
    htmlItalic { gui = "italic", }, -- htmlItalic     xxx cterm=italic gui=italic
    htmlItalicBold { htmlBoldItalic }, -- htmlItalicBold xxx links to htmlBoldItalic
    htmlItalicBoldUnderline { htmlBoldUnderlineItalic }, -- htmlItalicBoldUnderline xxx links to htmlBoldUnderlineItalic
    htmlItalicUnderline { htmlUnderlineItalic }, -- htmlItalicUnderline xxx links to htmlUnderlineItalic
    htmlItalicUnderlineBold { htmlBoldUnderlineItalic }, -- htmlItalicUnderlineBold xxx links to htmlBoldUnderlineItalic
    htmlLink { Underlined }, -- htmlLink       xxx links to Underlined
    htmlPreAttr { String }, -- htmlPreAttr    xxx links to String
    htmlPreError { Error }, -- htmlPreError   xxx links to Error
    htmlPreProc { PreProc }, -- htmlPreProc    xxx links to PreProc
    htmlPreProcAttrError { Error }, -- htmlPreProcAttrError xxx links to Error
    htmlPreProcAttrName { PreProc }, -- htmlPreProcAttrName xxx links to PreProc
    htmlPreStmt { PreProc }, -- htmlPreStmt    xxx links to PreProc
    htmlScriptTag { htmlTag }, -- htmlScriptTag  xxx links to htmlTag
    htmlSpecialChar { gui = "italic", fg = "#67609c", }, -- htmlSpecialChar xxx ctermfg=103 gui=italic guifg=#67609c
    htmlStatement { Statement }, -- htmlStatement  xxx links to Statement
    htmlStrike { gui = "strikethrough", }, -- htmlStrike     xxx cterm=strikethrough gui=strikethrough
    htmlString { fg = "#8dc35b", }, -- htmlString     xxx ctermfg=222 guifg=#8dc35b
    htmlStyleArg { htmlString }, -- htmlStyleArg   xxx links to htmlString
    htmlTag { fg = "#d9c767", }, -- htmlTag        xxx ctermfg=222 guifg=#d9c767
    htmlTagName { fg = "#d9c767", }, -- htmlTagName    xxx ctermfg=222 guifg=#d9c767
    htmlTitle { Title }, -- htmlTitle      xxx links to Title
    htmlUnderline { gui = "underline", }, -- htmlUnderline  xxx cterm=underline gui=underline
    htmlUnderlineBold { htmlBoldUnderline }, -- htmlUnderlineBold xxx links to htmlBoldUnderline
    htmlUnderlineBoldItalic { htmlBoldUnderlineItalic }, -- htmlUnderlineBoldItalic xxx links to htmlBoldUnderlineItalic
    htmlUnderlineItalic { gui = "underline,italic", }, -- htmlUnderlineItalic xxx cterm=underline,italic gui=underline,italic
    htmlUnderlineItalicBold { htmlBoldUnderlineItalic }, -- htmlUnderlineItalicBold xxx links to htmlBoldUnderlineItalic
    htmlValue { String }, -- htmlValue      xxx links to String
    html_icon {}, -- html_icon      xxx ctermfg=13
    jadeClass { fg = "#9676ac", }, -- jadeClass      xxx ctermfg=103 guifg=#9676ac
    jadeId { gui = "italic", fg = "#67609c", }, -- jadeId         xxx ctermfg=103 gui=italic guifg=#67609c
    jadePipedText { fg = "#5e8759", }, -- jadePipedText  xxx ctermfg=65 guifg=#5e8759
    javaAnnotation { fg = "#d9c767", }, -- javaAnnotation xxx ctermfg=222 guifg=#d9c767
    javaScript { Special }, -- javaScript     xxx links to Special
    javaScriptBoolean { Boolean }, -- javaScriptBoolean xxx links to Boolean
    javaScriptBraces { Function }, -- javaScriptBraces xxx links to Function
    javaScriptBranch { Conditional }, -- javaScriptBranch xxx links to Conditional
    javaScriptCharacter { Character }, -- javaScriptCharacter xxx links to Character
    javaScriptComment { Comment }, -- javaScriptComment xxx links to Comment
    javaScriptCommentTodo { Todo }, -- javaScriptCommentTodo xxx links to Todo
    javaScriptConditional { Conditional }, -- javaScriptConditional xxx links to Conditional
    javaScriptConstant { Label }, -- javaScriptConstant xxx links to Label
    javaScriptEmbed { Special }, -- javaScriptEmbed xxx links to Special
    javaScriptError { Error }, -- javaScriptError xxx links to Error
    javaScriptFunction { gui = "bold", fg = "#c57825", }, -- javaScriptFunction xxx ctermfg=222 gui=bold guifg=#c57825
    javaScriptGlobal { Keyword }, -- javaScriptGlobal xxx links to Keyword
    javaScriptIdentifier { Identifier }, -- javaScriptIdentifier xxx links to Identifier
    javaScriptLabel { Label }, -- javaScriptLabel xxx links to Label
    javaScriptLineComment { Comment }, -- javaScriptLineComment xxx links to Comment
    javaScriptMember { Keyword }, -- javaScriptMember xxx links to Keyword
    javaScriptMessage { Keyword }, -- javaScriptMessage xxx links to Keyword
    javaScriptNull { Keyword }, -- javaScriptNull xxx links to Keyword
    javaScriptOperator { Operator }, -- javaScriptOperator xxx links to Operator
    javaScriptRailsFunction { gui = "bold", fg = "#3c4c72", }, -- javaScriptRailsFunction xxx cterm=bold ctermfg=59 gui=bold guifg=#3c4c72
    javaScriptRegexpString { String }, -- javaScriptRegexpString xxx links to String
    javaScriptReserved { Keyword }, -- javaScriptReserved xxx links to Keyword
    javaScriptSpecial { Special }, -- javaScriptSpecial xxx links to Special
    javaScriptStatement { Statement }, -- javaScriptStatement xxx links to Statement
    javaScriptStringD { String }, -- javaScriptStringD xxx links to String
    javaScriptStringS { String }, -- javaScriptStringS xxx links to String
    javaScriptStringT { String }, -- javaScriptStringT xxx links to String
    javaScriptType { Type }, -- javaScriptType xxx links to Type
    javaTypeDef { fg = "#d9c767", }, -- javaTypeDef    xxx ctermfg=222 guifg=#d9c767
    jsBlockComment { fg = "#5e8759", }, -- jsBlockComment xxx ctermfg=65 guifg=#5e8759
    jsComment { fg = "#8e9292", }, -- jsComment      xxx ctermfg=244 guifg=#8e9292
    jsCommonJs { gui = "bold", fg = "#c57825", }, -- jsCommonJs     xxx cterm=bold ctermfg=222 gui=bold guifg=#c57825
    jsDocTags { gui = "bold", fg = "#5e8759", }, -- jsDocTags      xxx cterm=bold ctermfg=65 gui=bold guifg=#5e8759
    jsDocType { gui = "bold", fg = "#5e8759", }, -- jsDocType      xxx cterm=bold ctermfg=65 gui=bold guifg=#5e8759
    jsFuncCall { fg = "#d9c767", }, -- jsFuncCall     xxx ctermfg=222 guifg=#d9c767
    jsFuncName { fg = "#d9c767", }, -- jsFuncName     xxx ctermfg=222 guifg=#d9c767
    jsFunction { gui = "bold", fg = "#c57825", }, -- jsFunction     xxx ctermfg=172 gui=bold guifg=#c57825
    jsFunctionKey { gui = "bold", fg = "#c57825", }, -- jsFunctionKey  xxx cterm=bold ctermfg=222 gui=bold guifg=#c57825
    jsGlobalObjects { gui = "bold", fg = "#9676ac", }, -- jsGlobalObjects xxx cterm=bold ctermfg=103 gui=bold guifg=#9676ac
    jsObjectKey { gui = "bold", fg = "#9676ac", }, -- jsObjectKey    xxx cterm=bold ctermfg=103 gui=bold guifg=#9676ac
    jsParen { bg = "#2b2b2b", fg = "#a9b7c6", }, -- jsParen        xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    js_icon {}, -- js_icon        xxx ctermfg=11
    jsonBraces { bg = "#2b2b2b", fg = "#a9b7c6", }, -- jsonBraces     xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    lCursor { bg = "fg", fg = "bg", }, -- lCursor        xxx guifg=bg guibg=fg
    lualine_a_inactive { bg = "#3c3c3c", gui = "bold", fg = "#d4d4d4", }, -- lualine_a_inactive xxx cterm=bold ctermfg=188 ctermbg=237 gui=bold guifg=#d4d4d4 guibg=#3c3c3c
    lualine_a_insert { bg = "#569cd6", gui = "bold", fg = "#262626", }, -- lualine_a_insert xxx cterm=bold ctermfg=235 ctermbg=74 gui=bold guifg=#262626 guibg=#569cd6
    lualine_a_normal { bg = "#608b4e", gui = "bold", fg = "#262626", }, -- lualine_a_normal xxx cterm=bold ctermfg=235 ctermbg=65 gui=bold guifg=#262626 guibg=#608b4e
    lualine_a_replace { bg = "#d16969", gui = "bold", fg = "#262626", }, -- lualine_a_replace xxx cterm=bold ctermfg=235 ctermbg=167 gui=bold guifg=#262626 guibg=#d16969
    lualine_a_visual { bg = "#c586c0", gui = "bold", fg = "#262626", }, -- lualine_a_visual xxx cterm=bold ctermfg=235 ctermbg=175 gui=bold guifg=#262626 guibg=#c586c0
    lualine_b_diagnostics_error_command { bg = "#262626", fg = "#ff0000", }, -- lualine_b_diagnostics_error_command xxx ctermfg=9 ctermbg=235 guifg=#ff0000 guibg=#262626
    lualine_b_diagnostics_error_inactive { bg = "#569cd6", fg = "#ff0000", }, -- lualine_b_diagnostics_error_inactive xxx ctermfg=9 ctermbg=74 guifg=#ff0000 guibg=#569cd6
    lualine_b_diagnostics_error_insert { bg = "#262626", fg = "#ff0000", }, -- lualine_b_diagnostics_error_insert xxx ctermfg=9 ctermbg=235 guifg=#ff0000 guibg=#262626
    lualine_b_diagnostics_error_normal { bg = "#262626", fg = "#ff0000", }, -- lualine_b_diagnostics_error_normal xxx ctermfg=9 ctermbg=235 guifg=#ff0000 guibg=#262626
    lualine_b_diagnostics_error_replace { bg = "#262626", fg = "#ff0000", }, -- lualine_b_diagnostics_error_replace xxx ctermfg=9 ctermbg=235 guifg=#ff0000 guibg=#262626
    lualine_b_diagnostics_error_terminal { bg = "#262626", fg = "#ff0000", }, -- lualine_b_diagnostics_error_terminal xxx ctermfg=9 ctermbg=235 guifg=#ff0000 guibg=#262626
    lualine_b_diagnostics_error_visual { bg = "#262626", fg = "#ff0000", }, -- lualine_b_diagnostics_error_visual xxx ctermfg=9 ctermbg=235 guifg=#ff0000 guibg=#262626
    lualine_b_diagnostics_hint_command { bg = "#262626", fg = "#d3d3d3", }, -- lualine_b_diagnostics_hint_command xxx ctermfg=252 ctermbg=235 guifg=#d3d3d3 guibg=#262626
    lualine_b_diagnostics_hint_inactive { bg = "#569cd6", fg = "#d3d3d3", }, -- lualine_b_diagnostics_hint_inactive xxx ctermfg=252 ctermbg=74 guifg=#d3d3d3 guibg=#569cd6
    lualine_b_diagnostics_hint_insert { bg = "#262626", fg = "#d3d3d3", }, -- lualine_b_diagnostics_hint_insert xxx ctermfg=252 ctermbg=235 guifg=#d3d3d3 guibg=#262626
    lualine_b_diagnostics_hint_normal { bg = "#262626", fg = "#d3d3d3", }, -- lualine_b_diagnostics_hint_normal xxx ctermfg=252 ctermbg=235 guifg=#d3d3d3 guibg=#262626
    lualine_b_diagnostics_hint_replace { bg = "#262626", fg = "#d3d3d3", }, -- lualine_b_diagnostics_hint_replace xxx ctermfg=252 ctermbg=235 guifg=#d3d3d3 guibg=#262626
    lualine_b_diagnostics_hint_terminal { bg = "#262626", fg = "#d3d3d3", }, -- lualine_b_diagnostics_hint_terminal xxx ctermfg=252 ctermbg=235 guifg=#d3d3d3 guibg=#262626
    lualine_b_diagnostics_hint_visual { bg = "#262626", fg = "#d3d3d3", }, -- lualine_b_diagnostics_hint_visual xxx ctermfg=252 ctermbg=235 guifg=#d3d3d3 guibg=#262626
    lualine_b_diagnostics_info_command { bg = "#262626", fg = "#add8e6", }, -- lualine_b_diagnostics_info_command xxx ctermfg=152 ctermbg=235 guifg=#add8e6 guibg=#262626
    lualine_b_diagnostics_info_inactive { bg = "#569cd6", fg = "#add8e6", }, -- lualine_b_diagnostics_info_inactive xxx ctermfg=152 ctermbg=74 guifg=#add8e6 guibg=#569cd6
    lualine_b_diagnostics_info_insert { bg = "#262626", fg = "#add8e6", }, -- lualine_b_diagnostics_info_insert xxx ctermfg=152 ctermbg=235 guifg=#add8e6 guibg=#262626
    lualine_b_diagnostics_info_normal { bg = "#262626", fg = "#add8e6", }, -- lualine_b_diagnostics_info_normal xxx ctermfg=152 ctermbg=235 guifg=#add8e6 guibg=#262626
    lualine_b_diagnostics_info_replace { bg = "#262626", fg = "#add8e6", }, -- lualine_b_diagnostics_info_replace xxx ctermfg=152 ctermbg=235 guifg=#add8e6 guibg=#262626
    lualine_b_diagnostics_info_terminal { bg = "#262626", fg = "#add8e6", }, -- lualine_b_diagnostics_info_terminal xxx ctermfg=152 ctermbg=235 guifg=#add8e6 guibg=#262626
    lualine_b_diagnostics_info_visual { bg = "#262626", fg = "#add8e6", }, -- lualine_b_diagnostics_info_visual xxx ctermfg=152 ctermbg=235 guifg=#add8e6 guibg=#262626
    lualine_b_diagnostics_warn_command { bg = "#262626", fg = "#ffa500", }, -- lualine_b_diagnostics_warn_command xxx ctermfg=214 ctermbg=235 guifg=#ffa500 guibg=#262626
    lualine_b_diagnostics_warn_inactive { bg = "#569cd6", fg = "#ffa500", }, -- lualine_b_diagnostics_warn_inactive xxx ctermfg=214 ctermbg=74 guifg=#ffa500 guibg=#569cd6
    lualine_b_diagnostics_warn_insert { bg = "#262626", fg = "#ffa500", }, -- lualine_b_diagnostics_warn_insert xxx ctermfg=214 ctermbg=235 guifg=#ffa500 guibg=#262626
    lualine_b_diagnostics_warn_normal { bg = "#262626", fg = "#ffa500", }, -- lualine_b_diagnostics_warn_normal xxx ctermfg=214 ctermbg=235 guifg=#ffa500 guibg=#262626
    lualine_b_diagnostics_warn_replace { bg = "#262626", fg = "#ffa500", }, -- lualine_b_diagnostics_warn_replace xxx ctermfg=214 ctermbg=235 guifg=#ffa500 guibg=#262626
    lualine_b_diagnostics_warn_terminal { bg = "#262626", fg = "#ffa500", }, -- lualine_b_diagnostics_warn_terminal xxx ctermfg=214 ctermbg=235 guifg=#ffa500 guibg=#262626
    lualine_b_diagnostics_warn_visual { bg = "#262626", fg = "#ffa500", }, -- lualine_b_diagnostics_warn_visual xxx ctermfg=214 ctermbg=235 guifg=#ffa500 guibg=#262626
    lualine_b_diff_added_command { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_added_command xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_added_inactive { bg = "#569cd6", fg = "#a9b7c6", }, -- lualine_b_diff_added_inactive xxx ctermfg=146 ctermbg=74 guifg=#a9b7c6 guibg=#569cd6
    lualine_b_diff_added_insert { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_added_insert xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_added_normal { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_added_normal xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_added_replace { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_added_replace xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_added_terminal { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_added_terminal xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_added_visual { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_added_visual xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_modified_command { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_modified_command xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_modified_inactive { bg = "#569cd6", fg = "#a9b7c6", }, -- lualine_b_diff_modified_inactive xxx ctermfg=146 ctermbg=74 guifg=#a9b7c6 guibg=#569cd6
    lualine_b_diff_modified_insert { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_modified_insert xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_modified_normal { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_modified_normal xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_modified_replace { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_modified_replace xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_modified_terminal { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_modified_terminal xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_modified_visual { bg = "#262626", fg = "#a9b7c6", }, -- lualine_b_diff_modified_visual xxx ctermfg=146 ctermbg=235 guifg=#a9b7c6 guibg=#262626
    lualine_b_diff_removed_command { bg = "#262626", fg = "#8c0909", }, -- lualine_b_diff_removed_command xxx ctermfg=95 ctermbg=235 guifg=#8c0909 guibg=#262626
    lualine_b_diff_removed_inactive { bg = "#569cd6", fg = "#8c0909", }, -- lualine_b_diff_removed_inactive xxx ctermfg=95 ctermbg=74 guifg=#8c0909 guibg=#569cd6
    lualine_b_diff_removed_insert { bg = "#262626", fg = "#8c0909", }, -- lualine_b_diff_removed_insert xxx ctermfg=95 ctermbg=235 guifg=#8c0909 guibg=#262626
    lualine_b_diff_removed_normal { bg = "#262626", fg = "#8c0909", }, -- lualine_b_diff_removed_normal xxx ctermfg=95 ctermbg=235 guifg=#8c0909 guibg=#262626
    lualine_b_diff_removed_replace { bg = "#262626", fg = "#8c0909", }, -- lualine_b_diff_removed_replace xxx ctermfg=95 ctermbg=235 guifg=#8c0909 guibg=#262626
    lualine_b_diff_removed_terminal { bg = "#262626", fg = "#8c0909", }, -- lualine_b_diff_removed_terminal xxx ctermfg=95 ctermbg=235 guifg=#8c0909 guibg=#262626
    lualine_b_diff_removed_visual { bg = "#262626", fg = "#8c0909", }, -- lualine_b_diff_removed_visual xxx ctermfg=95 ctermbg=235 guifg=#8c0909 guibg=#262626
    lualine_b_inactive { bg = "#569cd6", fg = "#262626", }, -- lualine_b_inactive xxx ctermfg=235 ctermbg=74 guifg=#262626 guibg=#569cd6
    lualine_b_insert { bg = "#262626", fg = "#569cd6", }, -- lualine_b_insert xxx ctermfg=74 ctermbg=235 guifg=#569cd6 guibg=#262626
    lualine_b_normal { bg = "#262626", fg = "#608b4e", }, -- lualine_b_normal xxx ctermfg=65 ctermbg=235 guifg=#608b4e guibg=#262626
    lualine_b_replace { bg = "#262626", fg = "#d16969", }, -- lualine_b_replace xxx ctermfg=167 ctermbg=235 guifg=#d16969 guibg=#262626
    lualine_b_visual { bg = "#262626", fg = "#c586c0", }, -- lualine_b_visual xxx ctermfg=175 ctermbg=235 guifg=#c586c0 guibg=#262626
    lualine_c_insert { bg = "#262626", fg = "#d4d4d4", }, -- lualine_c_insert xxx ctermfg=188 ctermbg=235 guifg=#d4d4d4 guibg=#262626
    lualine_c_normal { bg = "#262626", fg = "#d4d4d4", }, -- lualine_c_normal xxx ctermfg=188 ctermbg=235 guifg=#d4d4d4 guibg=#262626
    lualine_c_replace { bg = "#262626", fg = "#d4d4d4", }, -- lualine_c_replace xxx ctermfg=188 ctermbg=235 guifg=#d4d4d4 guibg=#262626
    lualine_transitional_lualine_a_normal_to_lualine_b_normal { bg = "#262626", fg = "#608b4e", }, -- lualine_transitional_lualine_a_normal_to_lualine_b_normal xxx ctermfg=65 ctermbg=235 guifg=#608b4e guibg=#262626
    lualine_x_filetype_DevIconRb_command { bg = "#262626", fg = "#701516", }, -- lualine_x_filetype_DevIconRb_command xxx ctermfg=242 ctermbg=235 guifg=#701516 guibg=#262626
    lualine_x_filetype_DevIconRb_inactive { bg = "#262626", fg = "#701516", }, -- lualine_x_filetype_DevIconRb_inactive xxx ctermfg=242 ctermbg=235 guifg=#701516 guibg=#262626
    lualine_x_filetype_DevIconRb_insert { bg = "#262626", fg = "#701516", }, -- lualine_x_filetype_DevIconRb_insert xxx ctermfg=242 ctermbg=235 guifg=#701516 guibg=#262626
    lualine_x_filetype_DevIconRb_normal { bg = "#262626", fg = "#701516", }, -- lualine_x_filetype_DevIconRb_normal xxx ctermfg=242 ctermbg=235 guifg=#701516 guibg=#262626
    lualine_x_filetype_DevIconRb_replace { bg = "#262626", fg = "#701516", }, -- lualine_x_filetype_DevIconRb_replace xxx ctermfg=242 ctermbg=235 guifg=#701516 guibg=#262626
    lualine_x_filetype_DevIconRb_terminal { bg = "#262626", fg = "#701516", }, -- lualine_x_filetype_DevIconRb_terminal xxx ctermfg=242 ctermbg=235 guifg=#701516 guibg=#262626
    lualine_x_filetype_DevIconRb_visual { bg = "#262626", fg = "#701516", }, -- lualine_x_filetype_DevIconRb_visual xxx ctermfg=242 ctermbg=235 guifg=#701516 guibg=#262626
    markdownH1 { fg = "#c57825", }, -- markdownH1     xxx ctermfg=222 guifg=#c57825
    markdownH2 { fg = "#c57825", }, -- markdownH2     xxx ctermfg=222 guifg=#c57825
    markdownH3 { fg = "#c57825", }, -- markdownH3     xxx ctermfg=222 guifg=#c57825
    markdownH4 { fg = "#c57825", }, -- markdownH4     xxx ctermfg=222 guifg=#c57825
    markdownH5 { fg = "#c57825", }, -- markdownH5     xxx ctermfg=222 guifg=#c57825
    markdownH6 { fg = "#c57825", }, -- markdownH6     xxx ctermfg=222 guifg=#c57825
    markdownHeadingDelimiter { gui = "bold", fg = "#c57825", }, -- markdownHeadingDelimiter xxx ctermfg=172 gui=bold guifg=#c57825
    node_icon {}, -- node_icon      xxx ctermfg=10
    pythonOperator { gui = "bold", fg = "#c57825", }, -- pythonOperator xxx ctermfg=172 gui=bold guifg=#c57825
    rb_icon {}, -- rb_icon        xxx ctermfg=9
    rubyAction { rubyControl }, -- rubyAction     xxx links to rubyControl
    rubyAssertion { rubyException }, -- rubyAssertion  xxx links to rubyException
    rubyBeginEnd { Statement }, -- rubyBeginEnd   xxx links to Statement
    rubyBoolean { Boolean }, -- rubyBoolean    xxx links to Boolean
    rubyCharacter { Character }, -- rubyCharacter  xxx links to Character
    rubyClass { gui = "bold", fg = "#c57825", }, -- rubyClass      xxx ctermfg=172 gui=bold guifg=#c57825
    rubyClassName { rubyConstant }, -- rubyClassName  xxx links to rubyConstant
    rubyComment { Comment }, -- rubyComment    xxx links to Comment
    rubyConditional { Conditional }, -- rubyConditional xxx links to Conditional
    rubyConstant { gui = "bold", fg = "#9676ac", }, -- rubyConstant   xxx cterm=bold ctermfg=68 gui=bold guifg=#9676ac
    rubyControl { gui = "bold", fg = "#c57825", }, -- rubyControl    xxx ctermfg=172 gui=bold guifg=#c57825
    rubyData { Comment }, -- rubyData       xxx links to Comment
    rubyDefine { Define }, -- rubyDefine     xxx links to Define
    rubyDefinedOperator { rubyOperator }, -- rubyDefinedOperator xxx links to rubyOperator
    rubyDocumentation { Comment }, -- rubyDocumentation xxx links to Comment
    rubyEncoding { Constant }, -- rubyEncoding   xxx links to Constant
    rubyEnglishBooleanOperator { rubyOperator }, -- rubyEnglishBooleanOperator xxx links to rubyOperator
    rubyError { Error }, -- rubyError      xxx links to Error
    rubyEscape { gui = "bold", fg = "#c57825", }, -- rubyEscape     xxx ctermfg=172 gui=bold guifg=#c57825
    rubyEval { Statement }, -- rubyEval       xxx links to Statement
    rubyException { gui = "bold", fg = "#c57825", }, -- rubyException  xxx ctermfg=172 gui=bold guifg=#c57825
    rubyFloat { Float }, -- rubyFloat      xxx links to Float
    rubyFunction { gui = "bold", fg = "#c57825", }, -- rubyFunction   xxx cterm=bold ctermfg=222 gui=bold guifg=#c57825
    rubyGlobalVariable { fg = "#318495", }, -- rubyGlobalVariable xxx ctermfg=66 guifg=#318495
    rubyHelper { Function }, -- rubyHelper     xxx links to Function
    rubyHeredocDelimiter { rubyStringDelimiter }, -- rubyHeredocDelimiter xxx links to rubyStringDelimiter
    rubyIdentifier { Identifier }, -- rubyIdentifier xxx links to Identifier
    rubyInclude { gui = "bold", fg = "#c57825", }, -- rubyInclude    xxx ctermfg=172 gui=bold guifg=#c57825
    rubyInstanceVariable { fg = "#318495", }, -- rubyInstanceVariable xxx ctermfg=66 guifg=#318495
    rubyInteger { Number }, -- rubyInteger    xxx links to Number
    rubyKeyword { Keyword }, -- rubyKeyword    xxx links to Keyword
    rubyMethodName { rubyFunction }, -- rubyMethodName xxx links to rubyFunction
    rubyModuleName { rubyConstant }, -- rubyModuleName xxx links to rubyConstant
    rubyOperator { gui = "bold", fg = "#c57825", }, -- rubyOperator   xxx ctermfg=172 gui=bold guifg=#c57825
    rubyPercentRegexpDelimiter { rubyRegexpDelimiter }, -- rubyPercentRegexpDelimiter xxx links to rubyRegexpDelimiter
    rubyPercentStringDelimiter { rubyStringDelimiter }, -- rubyPercentStringDelimiter xxx links to rubyStringDelimiter
    rubyPseudoVariable { fg = "#318495", }, -- rubyPseudoVariable xxx ctermfg=66 guifg=#318495
    rubyRailsARAssociationMethod { gui = "bold", fg = "#3c4c72", }, -- rubyRailsARAssociationMethod xxx cterm=bold ctermfg=59 gui=bold guifg=#3c4c72
    rubyRailsARMethod { gui = "bold", fg = "#3c4c72", }, -- rubyRailsARMethod xxx cterm=bold ctermfg=59 gui=bold guifg=#3c4c72
    rubyRailsMethod { gui = "bold", fg = "#3c4c72", }, -- rubyRailsMethod xxx cterm=bold ctermfg=59 gui=bold guifg=#3c4c72
    rubyRailsRenderMethod { gui = "bold", fg = "#3c4c72", }, -- rubyRailsRenderMethod xxx cterm=bold ctermfg=59 gui=bold guifg=#3c4c72
    rubyRailsUserClass { gui = "bold", fg = "#bbbbbb", }, -- rubyRailsUserClass xxx cterm=bold ctermfg=256 gui=bold guifg=#bbbbbb
    rubyRegexp { fg = "#5e8759", }, -- rubyRegexp     xxx ctermfg=65 guifg=#5e8759
    rubyRegexpComment { Comment }, -- rubyRegexpComment xxx links to Comment
    rubyRegexpDelimiter { fg = "#5e8759", }, -- rubyRegexpDelimiter xxx ctermfg=65 guifg=#5e8759
    rubyRegexpSpecial { Special }, -- rubyRegexpSpecial xxx links to Special
    rubyResponse { rubyControl }, -- rubyResponse   xxx links to rubyControl
    rubyRoute { rubyControl }, -- rubyRoute      xxx links to rubyControl
    rubySchema { rubyControl }, -- rubySchema     xxx links to rubyControl
    rubySharpBang { PreProc }, -- rubySharpBang  xxx links to PreProc
    rubyString { String }, -- rubyString     xxx links to String
    rubyStringDelimiter { fg = "#5e8759", }, -- rubyStringDelimiter xxx ctermfg=65 guifg=#5e8759
    rubyStringEscape { Special }, -- rubyStringEscape xxx links to Special
    rubySymbol { gui = "italic", fg = "#67609c", }, -- rubySymbol     xxx ctermfg=103 gui=italic guifg=#67609c
    rubySymbolDelimiter { rubySymbol }, -- rubySymbolDelimiter xxx links to rubySymbol
    rubyTestAction { rubyControl }, -- rubyTestAction xxx links to rubyControl
    rubyTodo { Todo }, -- rubyTodo       xxx links to Todo
    vbBoolean { Boolean }, -- vbBoolean      xxx links to Boolean
    vbComment { Comment }, -- vbComment      xxx links to Comment
    vbConditional { Conditional }, -- vbConditional  xxx links to Conditional
    vbConst { Constant }, -- vbConst        xxx links to Constant
    vbDefine { Constant }, -- vbDefine       xxx links to Constant
    vbError { Error }, -- vbError        xxx links to Error
    vbEvents { Special }, -- vbEvents       xxx links to Special
    vbFloat { Float }, -- vbFloat        xxx links to Float
    vbFunction { Identifier }, -- vbFunction     xxx links to Identifier
    vbIdentifier { Identifier }, -- vbIdentifier   xxx links to Identifier
    vbKeyword { Statement }, -- vbKeyword      xxx links to Statement
    vbLineLabel { Comment }, -- vbLineLabel    xxx links to Comment
    vbLineNumber { Comment }, -- vbLineNumber   xxx links to Comment
    vbMethods { PreProc }, -- vbMethods      xxx links to PreProc
    vbNumber { Number }, -- vbNumber       xxx links to Number
    vbOperator { Operator }, -- vbOperator     xxx links to Operator
    vbPreProc { PreProc }, -- vbPreProc      xxx links to PreProc
    vbStatement { Statement }, -- vbStatement    xxx links to Statement
    vbString { String }, -- vbString       xxx links to String
    vbTodo { Todo }, -- vbTodo         xxx links to Todo
    vbTypeSpecifier { Type }, -- vbTypeSpecifier xxx links to Type
    vbTypes { Type }, -- vbTypes        xxx links to Type
    vimCommand { fg = "#c57825", }, -- vimCommand     xxx ctermfg=172 guifg=#c57825
    vimFuncName { fg = "#a9b7c6", }, -- vimFuncName    xxx ctermfg=103 guifg=#a9b7c6
    vimIsCommand { bg = "#2b2b2b", fg = "#a9b7c6", }, -- vimIsCommand   xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    vimOption { fg = "#d9c767", }, -- vimOption      xxx ctermfg=222 guifg=#d9c767
    vimParenSep { bg = "#2b2b2b", fg = "#a9b7c6", }, -- vimParenSep    xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    vimUserFunc { fg = "#d9c767", }, -- vimUserFunc    xxx ctermfg=222 guifg=#d9c767
    vimVar { bg = "#2b2b2b", fg = "#a9b7c6", }, -- vimVar         xxx ctermfg=188 ctermbg=235 guifg=#a9b7c6 guibg=#2b2b2b
    yamlAlias { fg = "#7ca8c6", }, -- yamlAlias      xxx ctermfg=67 guifg=#7ca8c6
    yamlAnchor { fg = "#7ca8c6", }, -- yamlAnchor     xxx ctermfg=67 guifg=#7ca8c6
    yamlBlockCollectionItemStart { Label }, -- yamlBlockCollectionItemStart xxx links to Label
    yamlBlockMappingKey { Identifier }, -- yamlBlockMappingKey xxx links to Identifier
    yamlBlockMappingMerge { Special }, -- yamlBlockMappingMerge xxx links to Special
    yamlComment { Comment }, -- yamlComment    xxx links to Comment
    yamlConstant { Constant }, -- yamlConstant   xxx links to Constant
    yamlDirectiveName { Keyword }, -- yamlDirectiveName xxx links to Keyword
    yamlDocumentEnd { PreProc }, -- yamlDocumentEnd xxx links to PreProc
    yamlDocumentHeader { bg = "#292929", }, -- yamlDocumentHeader xxx ctermbg=235 guibg=#292929
    yamlDocumentStart { PreProc }, -- yamlDocumentStart xxx links to PreProc
    yamlFloat { Float }, -- yamlFloat      xxx links to Float
    yamlFlowIndicator { Special }, -- yamlFlowIndicator xxx links to Special
    yamlFlowMappingKey { Identifier }, -- yamlFlowMappingKey xxx links to Identifier
    yamlFlowMappingMerge { Special }, -- yamlFlowMappingMerge xxx links to Special
    yamlInteger { Number }, -- yamlInteger    xxx links to Number
    yamlKeyValueDelimiter { Special }, -- yamlKeyValueDelimiter xxx links to Special
    yamlMappingKeyStart { Special }, -- yamlMappingKeyStart xxx links to Special
    yamlNodeTag { Type }, -- yamlNodeTag    xxx links to Type
    yamlReservedDirective { Error }, -- yamlReservedDirective xxx links to Error
    yamlString { String }, -- yamlString     xxx links to String
    yamlTagHandle { String }, -- yamlTagHandle  xxx links to String
    yamlTagPrefix { String }, -- yamlTagPrefix  xxx links to String
    yamlTimestamp { Number }, -- yamlTimestamp  xxx links to Number
    yamlTodo { Todo }, -- yamlTodo       xxx links to Todo
    yamlYAMLVersion { Number }, -- yamlYAMLVersion xxx links to Number
  }
end)
return theme
